version: '3.7'
 
services:
  db:
    image: postgres:16.2-alpine
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=pw"
      - "POSTGRES_DB=nesttest"
      - "TZ=Asia/Seoul"
    networks:
      - mogakoffee

  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DATABASE_URL = "postgresql://postgres:pw@db:5432/nesttest?schema=public"
    depends_on:
      - db
    ports:
      - "3000:3000"
    networks:
      - mogakoffee
    command: ["bash", "-c", "npx prisma db push && yarn start:dev"]

networks:
  mogakoffee:
      driver: bridge
  